id = "fwl"
name = "Francisco's Workflow Language"
version = "0.0.1"
schema_version = 1
authors = ["Francisco Serrano Baptista <francisco.baptista@gmail.com"]
description = "Frnacisco's Workflow Language is a simple grammar for the WorkflowAI Application. The Grammar presented here serves as an extension for the Zed Editor. This extension provides syntax highlighting and code completion for the WorkflowAI Application."

[grammars.fwl]
repository = "https://github.com/FranciscoSerranoBaptista/fwl"
commit = "138fcb9dc16f4ee8efcd933267f3d7e3c8011349"
